import { CategoryId } from './category.enum';

export const Rooms = {
    [CategoryId.Cafe]: [
        {
            id: '3nyuWu7dnTM',
            name: 'Real Time Cafe Vlog',
            creator: 'Laura Angelia',
            link: 'https://www.youtube.com/watch?v=3nyuWu7dnTM&ab_channel=LauraAngelia',
            category: CategoryId.Cafe,
        },
        {
            id: 'ig_QimWip34',
            name: 'Starbucks reserve',
            creator: 'Walking Air',
            link: 'https://www.youtube.com/watch?v=ig_QimWip34&ab_channel=WalkingAir',
            category: CategoryId.Cafe,
        },
        {
            id: 'PDDkze546nQ',
            name: 'Seoul cafe 2',
            creator: 'Jun`s Cafe Stroll',
            link: 'https://www.youtube.com/watch?v=PDDkze546nQ&ab_channel=Jun%27sCafeStroll',
            category: CategoryId.Cafe,
        },
        {
            id: 'ql32tlC7eqw',
            name: 'Patio',
            creator: 'Ozz`s study corner',
            link: 'https://www.youtube.com/watch?v=ql32tlC7eqw&ab_channel=ozz%27sstudycorner%F0%9F%93%9A%E2%98%95%EF%B8%8F',
            category: CategoryId.Cafe,
        },
        {
            id: '7sg-dfYLGRQ',
            name: 'Vancouver Starbucks',
            creator: '평범남B',
            link: 'https://www.youtube.com/watch?v=7sg-dfYLGRQ&ab_channel=%ED%8F%89%EB%B2%94%EB%82%A8B',
            category: CategoryId.Cafe,
        },
        {
            id: 'AVnfqiiyRK0',
            name: 'Seoul cafe',
            creator: 'Jun`s Cafe Stroll',
            link: 'https://www.youtube.com/watch?v=AVnfqiiyRK0&ab_channel=Jun%27sCafeStroll',
            category: CategoryId.Cafe,
        },
        {
            id: 'qMHbh6XmgwM',
            name: 'Tokyo coffee shop',
            creator: 'Jun`s Cafe Stroll',
            link: 'https://www.youtube.com/watch?v=qMHbh6XmgwM&ab_channel=Jun%27sCafeStroll',
            category: CategoryId.Cafe,
        },
        {
            id: 'LUcdunOITak',
            name: 'Study with me in Gangnam',
            creator: 'K-study',
            link: 'https://www.youtube.com/watch?v=LUcdunOITak&ab_channel=K-Study%EC%BC%80%EC%9D%B4%EC%8A%A4%ED%84%B0%EB%94%94',
            category: CategoryId.Cafe,
        },
    ],
    [CategoryId.Beach]: [
        {
            id: 'sIbJ3aQPo2Y',
            name: 'Oregon Coast',
            creator: 'Nomadic Ambience',
            link: 'https://www.youtube.com/watch?v=sIbJ3aQPo2Y&ab_channel=NomadicAmbience',
            category: CategoryId.Beach,
        },
        {
            id: 'UyZfCrrdbm8',
            name: 'Tropical Beach',
            creator: 'TheSilentWatcher',
            link: 'https://www.youtube.com/watch?v=UyZfCrrdbm8&ab_channel=TheSilentWatcher',
            category: CategoryId.Beach,
        },
        {
            id: 'vpqImH1jCCk',
            name: 'Jeju Island',
            creator: 'K-study',
            link: 'https://www.youtube.com/watch?v=vpqImH1jCCk&ab_channel=K-Study%EC%BC%80%EC%9D%B4%EC%8A%A4%ED%84%B0%EB%94%94',
            category: CategoryId.Beach,
        },
        {
            id: 'B1T06UhcX0Q',
            name: 'Tropics',
            creator: 'LoungeV Films',
            link: 'https://www.youtube.com/watch?v=B1T06UhcX0Q&ab_channel=LoungeVFilms-RelaxingMusicandNatureSounds',
            category: CategoryId.Beach,
        },
    ],
    [CategoryId.City]: [
        {
            id: 'eZe4Q_58UTU',
            name: 'Walking in the Rain Manhattan',
            creator: 'Nomadic Ambience',
            link: 'https://www.youtube.com/watch?v=eZe4Q_58UTU&t=1711s&ab_channel=NomadicAmbience',
            category: CategoryId.City,
        },
        {
            id: 'lh8dNmneVyY',
            name: 'Downtown Vancouver, Canada',
            creator: '4K Urban Life',
            link: 'https://www.youtube.com/watch?v=lh8dNmneVyY',
            category: CategoryId.City,
        },
        {
            id: 'Vg1mpD1BICI',
            name: 'New York City open window',
            creator: 'Nomadic Ambience',
            link: 'https://www.youtube.com/watch?v=Vg1mpD1BICI&t=5774s&ab_channel=NomadicAmbience',
            category: CategoryId.City,
        },
        {
            id: '_dWyKj7I9JM',
            name: 'Shibuya Crossing at Night',
            creator: 'Nomadic Ambience',
            link: 'https://www.youtube.com/watch?v=_dWyKj7I9JM&ab_channel=NomadicAmbience',
            category: CategoryId.City,
        },
        {
            id: 'unfmzc0opk4',
            name: 'New York City ambience',
            creator: 'Nomadic Ambience',
            link: 'https://www.youtube.com/watch?v=unfmzc0opk4&ab_channel=NomadicAmbience',
            category: CategoryId.City,
        },
        {
            id: 'MGMqLGvtNpY',
            name: 'London, Great Britain',
            creator: '4K Urban Life',
            link: 'https://www.youtube.com/watch?v=MGMqLGvtNpY',
            category: CategoryId.City,
        },
        {
            id: 'hBGbt2CRDpA',
            name: 'Luxury Tokyo Hotel',
            creator: 'Ambient Renders',
            link: 'https://www.youtube.com/watch?v=hBGbt2CRDpA',
            category: CategoryId.City,
        },
    ],
    [CategoryId.Nature]: [
        {
            id: '=VESwpRKuO7o',
            name: 'Winter Mountain',
            creator: 'Nature Soundscapes',
            link: 'https://www.youtube.com/watch?v=VESwpRKuO7o&ab_channel=NatureSoundscapes',
            category: CategoryId.Nature,
        },
        {
            id: '6uhRxK_EOm4',
            name: 'Autumn River',
            creator: 'TheSilentWatcher',
            link: 'https://www.youtube.com/watch?v=6uhRxK_EOm4&ab_channel=TheSilentWatcher',
            category: CategoryId.Nature,
        },
        {
            id: 'qRTVg8HHzUo',
            name: 'Mount Shuksan',
            creator: 'Nature Soundscapes',
            link: 'https://www.youtube.com/watch?v=qRTVg8HHzUo&ab_channel=NatureSoundscapes',
            category: CategoryId.Nature,
        },
        {
            id: 'Nmmsl2X_--U',
            name: 'Birds Singing in the Forest',
            creator: 'Nature Soundscapes',
            link: 'https://www.youtube.com/watch?v=Nmmsl2X_--U&ab_channel=NatureSoundscapes',
            category: CategoryId.Nature,
        },
        {
            id: 'QQwyRqmIbzc',
            name: 'Summer Meadow',
            creator: 'Nature Soundscapes',
            link: 'https://www.youtube.com/watch?v=QQwyRqmIbzc&ab_channel=NatureSoundscapes',
            category: CategoryId.Nature,
        },
    ],
    [CategoryId.Christmas]: [
        {
            id: 'EoeONBEd15g',
            name: 'Santa`s Workshop',
            creator: 'The Jazz Hop Cafe',
            link: 'https://www.youtube.com/watch?v=EoeONBEd15g',
            category: CategoryId.Christmas,
        },
        {
            id: 'Rnx08JFs6nQ',
            name: 'Snowy Christmas Days',
            creator: 'Feardog',
            link: 'https://www.youtube.com/watch?v=Rnx08JFs6nQ',
            category: CategoryId.Christmas,
        },
        {
            id: '9a9GixtqVP4',
            name: 'Cozy Christmas Coffee Shop',
            creator: 'Calmed by Nature',
            link: 'https://www.youtube.com/watch?v=9a9GixtqVP4',
            category: CategoryId.Christmas,
        },
        {
            id: '12cMTeHHeic',
            name: 'Heavenly Christmas Ambience',
            creator: 'Cozy Corner',
            link: 'https://www.youtube.com/watch?v=12cMTeHHeic',
            category: CategoryId.Christmas,
        },
    ],
    [CategoryId.Walk]: [
        {
            id: '6uhRxK_EOm4',
            name: 'Autumn River',
            creator: 'TheSilentWatcher',
            link: 'https://www.youtube.com/watch?v=6uhRxK_EOm4&ab_channel=TheSilentWatcher',
            category: CategoryId.Nature,
        },
    ],
    [CategoryId.Window]: [],
    [CategoryId.Animated]: [
        {
            id: 'LG9D9UtaDYw',
            name: 'Study with Koya',
            creator: 'BT21',
            link: 'https://www.youtube.com/watch?v=LG9D9UtaDYw&ab_channel=BT21',
            category: CategoryId.Animated,
        },
        {
            id: 'DbuebKNKQsQ',
            name: 'A Peaceful Place',
            creator: 'The Jazz Hop Cafe',
            link: 'https://www.youtube.com/watch?v=DbuebKNKQsQ',
            category: CategoryId.Animated,
        },
        {
            id: '0dN2BZjVUpY',
            name: 'Season of Japan',
            creator: 'The Jazz Hop Cafe',
            link: 'https://www.youtube.com/watch?v=0dN2BZjVUpY',
            category: CategoryId.Animated,
        },

        {
            id: '-5KAN9_CzSA',
            name: 'Coffee shop radio',
            creator: 'STEEZYASFUCK',
            link: 'https://www.youtube.com/watch?v=-5KAN9_CzSA&ab_channel=STEEZYASFUCK',
            category: CategoryId.Animated,
        },
        {
            id: '5wRWniH7rt8',
            name: 'Cherry Blossom',
            creator: 'The Jazz Hop Cafe',
            link: 'https://www.youtube.com/watch?v=5wRWniH7rt8',
            category: CategoryId.Animated,
        },
        {
            id: 'ALja3wAdQsM',
            name: 'Side Streets',
            creator: 'The Jazz Hop Cafe',
            link: 'https://www.youtube.com/watch?v=ALja3wAdQsM',
            category: CategoryId.Animated,
        },
    ],
    [CategoryId.NewYears]: [
        {
            id: 'WgIsE3r5cuc',
            name: 'Worldwide Cities New Year`s Eve',
            creator: 'Fox Mooder AMBIENCE WORLDS',
            link: 'https://www.youtube.com/watch?v=WgIsE3r5cuc&ab_channel=ASMRWeekly',
            category: CategoryId.NewYears,
        },
        {
            id: 'CjfnP1Sds8o',
            name: 'New Year`s Eve Fireworks',
            creator: 'ASMR Weekly',
            link: 'https://www.youtube.com/watch?v=CjfnP1Sds8o&ab_channel=ASMRWeekly',
            category: CategoryId.NewYears,
        },
    ],
};
